name: SGS-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '0 21 * * *'
jobs:
  login:
    name: SGS-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install playwright
        run: |
          pip install playwright
          playwright install  # Ensure the required browsers are installed

      - name: Install Opencv
        run: pip install opencv-python

      - name: Install numpy
        run: pip install numpy

      - name: SGS login
        run: python login_cv.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}
